/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_vod_MainActivity */

#ifndef _Included_com_example_vod_MainActivity
#define _Included_com_example_vod_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_vod_MainActivity
 * Method:    output
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_vod_MainActivity_output
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_vod_MainActivity
 * Method:    input
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_vod_MainActivity_input
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
